apiVersion: v1
kind: Pod
metadata:
  name: k8s-rbac-example
spec:
  containers:
    - image: semihbkgr/k8s-rbas-example:1.0.1
      name: k8s-rbac-example
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          value: default
        - name: POD_NAME
          value: example-xxxxx
  serviceAccountName: example-service-account
