apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-rbac-example-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-rbac-example-cr
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-rbac-example-crb
roleRef:
  kind: ClusterRole
  name: kubernetes-rbac-example-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubernetes-rbac-example-sa
    namespace: default
